# -*- coding: utf-8 -*-
"""replication

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XZY3WEUO8EyXgpYi12n-72TuqqbtA6b1
"""

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Transformation to Wealth Real Time Motion Model</title>
<style>
  html, body {
    margin: 0;
    min-height: 100%;
    background: #02050a;
    overflow: auto;
  }

  svg {
    display: block;
    width: 100vw;
    height: auto;
    min-height: 100vh;
    background: radial-gradient(circle at 50% 12%, #102542 0%, #06101c 45%, #010309 100%);
    font-family: Arial, Helvetica, sans-serif;
  }

  .axis { stroke: rgba(190,235,255,.85); stroke-width: 2; fill: none; filter: drop-shadow(0 0 5px #00aaff); }
  .grid { stroke: rgba(90,180,255,.24); stroke-width: 1; fill: none; }
  .gridStrong { stroke: rgba(180,230,255,.45); stroke-width: 1.3; fill: none; }
  .label { fill: rgba(245,255,255,.96); font-size: 22px; font-weight: 600; }
  .tick { fill: rgba(245,255,255,.92); font-size: 16px; }
  .title { fill: rgba(245,255,255,.98); font-size: 30px; font-weight: 700; filter: drop-shadow(0 0 8px #3fbaff); }
  .colorbarText { fill: white; font-size: 17px; }
  .panelGlow { fill: rgba(4,20,40,.26); stroke: rgba(60,205,255,.55); stroke-width: 2; filter: drop-shadow(0 0 10px #008cff); }
  .stream { fill: none; stroke-width: 5; stroke-linecap: round; stroke-dasharray: 18 20; animation: flow 1.2s linear infinite; filter: drop-shadow(0 0 8px #00ffe0); }
  @keyframes flow { to { stroke-dashoffset: -76; } }

  .bar {
    stroke: rgba(255,255,255,.12);
    stroke-width: .7;
    transform-box: fill-box;
    transform-origin: center bottom;
    animation: pulseBar 1.6s ease-in-out infinite;
  }
  .randomBar { animation-name: pulseRandom; }
  .blockBar { animation-name: pulseBlock; }

  @keyframes pulseRandom {
    0%, 100% { transform: scaleY(.78); filter: brightness(.85) drop-shadow(0 0 1px #00d9ff); }
    50% { transform: scaleY(1.08); filter: brightness(1.35) drop-shadow(0 0 6px #ffff00); }
  }
  @keyframes pulseBlock {
    0%, 100% { transform: scaleY(.70); filter: brightness(.9) drop-shadow(0 0 2px #00c8ff); }
    50% { transform: scaleY(1.15); filter: brightness(1.45) drop-shadow(0 0 8px #ffff00); }
  }

  .scanDot { animation: dotPulse .9s ease-in-out infinite; }
  @keyframes dotPulse { 0%,100% { opacity:.35; r:4; } 50% { opacity:1; r:8; } }

  .spark { animation: sparkMove 4s linear infinite; opacity: .72; }
  @keyframes sparkMove {
    0% { transform: translate(0,0); opacity:.1; }
    20% { opacity:1; }
    100% { transform: translate(520px,-145px); opacity:.1; }
  }
</style>
</head>
<body>

<svg viewBox="0 0 1600 950" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="barGradLow" x1="0" y1="1" x2="0" y2="0">
      <stop offset="0%" stop-color="#14127a"/>
      <stop offset="45%" stop-color="#00b8aa"/>
      <stop offset="100%" stop-color="#fff600"/>
    </linearGradient>
    <linearGradient id="barGradMid" x1="0" y1="1" x2="0" y2="0">
      <stop offset="0%" stop-color="#130b5d"/>
      <stop offset="65%" stop-color="#00d18a"/>
      <stop offset="100%" stop-color="#eaff00"/>
    </linearGradient>
    <linearGradient id="colorbar" x1="0" y1="1" x2="0" y2="0">
      <stop offset="0%" stop-color="#210060"/>
      <stop offset="25%" stop-color="#1750b5"/>
      <stop offset="50%" stop-color="#00a6a7"/>
      <stop offset="75%" stop-color="#4bd450"/>
      <stop offset="100%" stop-color="#fff700"/>
    </linearGradient>
    <linearGradient id="streamGrad" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0%" stop-color="#00aaff"/>
      <stop offset="50%" stop-color="#00ffe0"/>
      <stop offset="100%" stop-color="#fff700"/>
    </linearGradient>
  </defs>

  <text x="465" y="95" class="title" text-anchor="middle">demo</text>
  <text x="1145" y="95" class="title" text-anchor="middle">demo</text>

  <!-- LEFT PANEL -->
  <g id="leftPanel" transform="translate(100 120)">
    <polygon class="panelGlow" points="40,520 555,610 690,480 175,390"/>
    <polygon class="gridStrong" points="40,160 555,250 690,120 175,30"/>
    <line class="axis" x1="40" y1="520" x2="40" y2="160"/>
    <line class="axis" x1="40" y1="520" x2="555" y2="610"/>
    <line class="axis" x1="555" y1="610" x2="690" y2="480"/>
    <line class="axis" x1="690" y1="480" x2="690" y2="120"/>
    <line class="axis" x1="40" y1="160" x2="175" y2="30"/>
    <line class="axis" x1="175" y1="30" x2="690" y2="120"/>

    <g>
      <line class="grid" x1="40" y1="448" x2="555" y2="538"/>
      <line class="grid" x1="40" y1="376" x2="555" y2="466"/>
      <line class="grid" x1="40" y1="304" x2="555" y2="394"/>
      <line class="grid" x1="40" y1="232" x2="555" y2="322"/>
      <line class="grid" x1="40" y1="448" x2="175" y2="318"/>
      <line class="grid" x1="40" y1="376" x2="175" y2="246"/>
      <line class="grid" x1="40" y1="304" x2="175" y2="174"/>
      <line class="grid" x1="40" y1="232" x2="175" y2="102"/>
      <line class="grid" x1="142" y1="538" x2="277" y2="408"/>
      <line class="grid" x1="245" y1="556" x2="380" y2="426"/>
      <line class="grid" x1="348" y1="574" x2="483" y2="444"/>
      <line class="grid" x1="451" y1="592" x2="586" y2="462"/>
    </g>

    <text x="310" y="675" class="label" text-anchor="middle" transform="rotate(10 310 675)">X Index</text>
    <text x="646" y="610" class="label" text-anchor="middle" transform="rotate(-58 646 610)">Y Index</text>
    <text x="-10" y="340" class="label" text-anchor="middle" transform="rotate(-90 -10 340)">Wealth Amount</text>

    <text x="25" y="525" class="tick" text-anchor="end">0.0</text>
    <text x="25" y="448" class="tick" text-anchor="end">0.2</text>
    <text x="25" y="376" class="tick" text-anchor="end">0.4</text>
    <text x="25" y="304" class="tick" text-anchor="end">0.6</text>
    <text x="25" y="232" class="tick" text-anchor="end">0.8</text>
    <text x="25" y="160" class="tick" text-anchor="end">1.0</text>

    <!-- bars are generated statically -->
    <g id="leftBars">
      <rect class="bar randomBar" x="70.0" y="455.0" width="18" height="45.0" fill="url(#barGradLow)" style="animation-delay:0.00s" transform="skewY(10)"/>
<rect class="bar randomBar" x="99.0" y="418.0" width="18" height="82.0" fill="url(#barGradLow)" style="animation-delay:-0.09s" transform="skewY(10)"/>
<rect class="bar randomBar" x="128.0" y="381.0" width="18" height="119.0" fill="url(#barGradLow)" style="animation-delay:-0.18s" transform="skewY(10)"/>
<rect class="bar randomBar" x="157.0" y="344.0" width="18" height="156.0" fill="url(#barGradLow)" style="animation-delay:-0.27s" transform="skewY(10)"/>
<rect class="bar randomBar" x="186.0" y="307.0" width="18" height="193.0" fill="url(#barGradLow)" style="animation-delay:-0.36s" transform="skewY(10)"/>
<rect class="bar randomBar" x="215.0" y="430.0" width="18" height="70.0" fill="url(#barGradLow)" style="animation-delay:-0.45s" transform="skewY(10)"/>
<rect class="bar randomBar" x="244.0" y="393.0" width="18" height="107.0" fill="url(#barGradLow)" style="animation-delay:-0.54s" transform="skewY(10)"/>
<rect class="bar randomBar" x="273.0" y="356.0" width="18" height="144.0" fill="url(#barGradLow)" style="animation-delay:-0.63s" transform="skewY(10)"/>
<rect class="bar randomBar" x="302.0" y="319.0" width="18" height="181.0" fill="url(#barGradLow)" style="animation-delay:-0.72s" transform="skewY(10)"/>
<rect class="bar randomBar" x="331.0" y="442.0" width="18" height="58.0" fill="url(#barGradLow)" style="animation-delay:-0.81s" transform="skewY(10)"/>
<rect class="bar randomBar" x="360.0" y="405.0" width="18" height="95.0" fill="url(#barGradLow)" style="animation-delay:-0.90s" transform="skewY(10)"/>
<rect class="bar randomBar" x="389.0" y="368.0" width="18" height="132.0" fill="url(#barGradLow)" style="animation-delay:-0.99s" transform="skewY(10)"/>
<rect class="bar randomBar" x="418.0" y="331.0" width="18" height="169.0" fill="url(#barGradLow)" style="animation-delay:-1.08s" transform="skewY(10)"/>
<rect class="bar randomBar" x="447.0" y="454.0" width="18" height="46.0" fill="url(#barGradLow)" style="animation-delay:-1.17s" transform="skewY(10)"/>
<rect class="bar randomBar" x="476.0" y="417.0" width="18" height="83.0" fill="url(#barGradLow)" style="animation-delay:-1.26s" transform="skewY(10)"/>
<rect class="bar randomBar" x="505.0" y="380.0" width="18" height="120.0" fill="url(#barGradLow)" style="animation-delay:-1.35s" transform="skewY(10)"/>
<rect class="bar randomBar" x="534.0" y="343.0" width="18" height="157.0" fill="url(#barGradLow)" style="animation-delay:-1.44s" transform="skewY(10)"/>
<rect class="bar randomBar" x="563.0" y="306.0" width="18" height="194.0" fill="url(#barGradLow)" style="animation-delay:0.00s" transform="skewY(10)"/>
<rect class="bar randomBar" x="77.0" y="429.0" width="18" height="71.0" fill="url(#barGradLow)" style="animation-delay:-0.09s" transform="skewY(10)"/>
<rect class="bar randomBar" x="106.0" y="392.0" width="18" height="108.0" fill="url(#barGradLow)" style="animation-delay:-0.18s" transform="skewY(10)"/>
<rect class="bar randomBar" x="135.0" y="355.0" width="18" height="145.0" fill="url(#barGradLow)" style="animation-delay:-0.27s" transform="skewY(10)"/>
<rect class="bar randomBar" x="164.0" y="318.0" width="18" height="182.0" fill="url(#barGradLow)" style="animation-delay:-0.36s" transform="skewY(10)"/>
<rect class="bar randomBar" x="193.0" y="441.0" width="18" height="59.0" fill="url(#barGradLow)" style="animation-delay:-0.45s" transform="skewY(10)"/>
<rect class="bar randomBar" x="222.0" y="404.0" width="18" height="96.0" fill="url(#barGradLow)" style="animation-delay:-0.54s" transform="skewY(10)"/>
<rect class="bar randomBar" x="251.0" y="367.0" width="18" height="133.0" fill="url(#barGradLow)" style="animation-delay:-0.63s" transform="skewY(10)"/>
<rect class="bar randomBar" x="280.0" y="330.0" width="18" height="170.0" fill="url(#barGradLow)" style="animation-delay:-0.72s" transform="skewY(10)"/>
<rect class="bar randomBar" x="309.0" y="453.0" width="18" height="47.0" fill="url(#barGradLow)" style="animation-delay:-0.81s" transform="skewY(10)"/>
<rect class="bar randomBar" x="338.0" y="416.0" width="18" height="84.0" fill="url(#barGradLow)" style="animation-delay:-0.90s" transform="skewY(10)"/>
<rect class="bar randomBar" x="367.0" y="379.0" width="18" height="121.0" fill="url(#barGradLow)" style="animation-delay:-0.99s" transform="skewY(10)"/>
<rect class="bar randomBar" x="396.0" y="342.0" width="18" height="158.0" fill="url(#barGradLow)" style="animation-delay:-1.08s" transform="skewY(10)"/>
<rect class="bar randomBar" x="425.0" y="305.0" width="18" height="195.0" fill="url(#barGradLow)" style="animation-delay:-1.17s" transform="skewY(10)"/>
<rect class="bar randomBar" x="454.0" y="428.0" width="18" height="72.0" fill="url(#barGradLow)" style="animation-delay:-1.26s" transform="skewY(10)"/>
<rect class="bar randomBar" x="483.0" y="391.0" width="18" height="109.0" fill="url(#barGradLow)" style="animation-delay:-1.35s" transform="skewY(10)"/>
<rect class="bar randomBar" x="512.0" y="354.0" width="18" height="146.0" fill="url(#barGradLow)" style="animation-delay:-1.44s" transform="skewY(10)"/>
<rect class="bar randomBar" x="541.0" y="317.0" width="18" height="183.0" fill="url(#barGradLow)" style="animation-delay:0.00s" transform="skewY(10)"/>
<rect class="bar randomBar" x="570.0" y="440.0" width="18" height="60.0" fill="url(#barGradLow)" style="animation-delay:-0.09s" transform="skewY(10)"/>
<rect class="bar randomBar" x="84.0" y="403.0" width="18" height="97.0" fill="url(#barGradLow)" style="animation-delay:-0.18s" transform="skewY(10)"/>
<rect class="bar randomBar" x="113.0" y="366.0" width="18" height="134.0" fill="url(#barGradLow)" style="animation-delay:-0.27s" transform="skewY(10)"/>
<rect class="bar randomBar" x="142.0" y="329.0" width="18" height="171.0" fill="url(#barGradLow)" style="animation-delay:-0.36s" transform="skewY(10)"/>
<rect class="bar randomBar" x="171.0" y="452.0" width="18" height="48.0" fill="url(#barGradLow)" style="animation-delay:-0.45s" transform="skewY(10)"/>
<rect class="bar randomBar" x="200.0" y="415.0" width="18" height="85.0" fill="url(#barGradLow)" style="animation-delay:-0.54s" transform="skewY(10)"/>
<rect class="bar randomBar" x="229.0" y="378.0" width="18" height="122.0" fill="url(#barGradLow)" style="animation-delay:-0.63s" transform="skewY(10)"/>
<rect class="bar randomBar" x="258.0" y="341.0" width="18" height="159.0" fill="url(#barGradLow)" style="animation-delay:-0.72s" transform="skewY(10)"/>
<rect class="bar randomBar" x="287.0" y="304.0" width="18" height="196.0" fill="url(#barGradLow)" style="animation-delay:-0.81s" transform="skewY(10)"/>
<rect class="bar randomBar" x="316.0" y="427.0" width="18" height="73.0" fill="url(#barGradLow)" style="animation-delay:-0.90s" transform="skewY(10)"/>
<rect class="bar randomBar" x="345.0" y="390.0" width="18" height="110.0" fill="url(#barGradLow)" style="animation-delay:-0.99s" transform="skewY(10)"/>
<rect class="bar randomBar" x="374.0" y="353.0" width="18" height="147.0" fill="url(#barGradLow)" style="animation-delay:-1.08s" transform="skewY(10)"/>
<rect class="bar randomBar" x="403.0" y="316.0" width="18" height="184.0" fill="url(#barGradLow)" style="animation-delay:-1.17s" transform="skewY(10)"/>
<rect class="bar randomBar" x="432.0" y="439.0" width="18" height="61.0" fill="url(#barGradLow)" style="animation-delay:-1.26s" transform="skewY(10)"/>
<rect class="bar randomBar" x="461.0" y="402.0" width="18" height="98.0" fill="url(#barGradLow)" style="animation-delay:-1.35s" transform="skewY(10)"/>
<rect class="bar randomBar" x="490.0" y="365.0" width="18" height="135.0" fill="url(#barGradLow)" style="animation-delay:-1.44s" transform="skewY(10)"/>
<rect class="bar randomBar" x="519.0" y="328.0" width="18" height="172.0" fill="url(#barGradLow)" style="animation-delay:0.00s" transform="skewY(10)"/>
<rect class="bar randomBar" x="548.0" y="451.0" width="18" height="49.0" fill="url(#barGradLow)" style="animation-delay:-0.09s" transform="skewY(10)"/>
<rect class="bar randomBar" x="577.0" y="414.0" width="18" height="86.0" fill="url(#barGradLow)" style="animation-delay:-0.18s" transform="skewY(10)"/>
<rect class="bar randomBar" x="91.0" y="377.0" width="18" height="123.0" fill="url(#barGradLow)" style="animation-delay:-0.27s" transform="skewY(10)"/>
<rect class="bar randomBar" x="120.0" y="340.0" width="18" height="160.0" fill="url(#barGradLow)" style="animation-delay:-0.36s" transform="skewY(10)"/>
<rect class="bar randomBar" x="149.0" y="303.0" width="18" height="197.0" fill="url(#barGradLow)" style="animation-delay:-0.45s" transform="skewY(10)"/>
<rect class="bar randomBar" x="178.0" y="426.0" width="18" height="74.0" fill="url(#barGradLow)" style="animation-delay:-0.54s" transform="skewY(10)"/>
<rect class="bar randomBar" x="207.0" y="389.0" width="18" height="111.0" fill="url(#barGradLow)" style="animation-delay:-0.63s" transform="skewY(10)"/>
<rect class="bar randomBar" x="236.0" y="352.0" width="18" height="148.0" fill="url(#barGradLow)" style="animation-delay:-0.72s" transform="skewY(10)"/>
<rect class="bar randomBar" x="265.0" y="315.0" width="18" height="185.0" fill="url(#barGradLow)" style="animation-delay:-0.81s" transform="skewY(10)"/>
<rect class="bar randomBar" x="294.0" y="438.0" width="18" height="62.0" fill="url(#barGradLow)" style="animation-delay:-0.90s" transform="skewY(10)"/>
<rect class="bar randomBar" x="323.0" y="401.0" width="18" height="99.0" fill="url(#barGradLow)" style="animation-delay:-0.99s" transform="skewY(10)"/>
<rect class="bar randomBar" x="352.0" y="364.0" width="18" height="136.0" fill="url(#barGradLow)" style="animation-delay:-1.08s" transform="skewY(10)"/>
<rect class="bar randomBar" x="381.0" y="327.0" width="18" height="173.0" fill="url(#barGradLow)" style="animation-delay:-1.17s" transform="skewY(10)"/>
<rect class="bar randomBar" x="410.0" y="450.0" width="18" height="50.0" fill="url(#barGradLow)" style="animation-delay:-1.26s" transform="skewY(10)"/>
<rect class="bar randomBar" x="439.0" y="413.0" width="18" height="87.0" fill="url(#barGradLow)" style="animation-delay:-1.35s" transform="skewY(10)"/>
<rect class="bar randomBar" x="468.0" y="376.0" width="18" height="124.0" fill="url(#barGradLow)" style="animation-delay:-1.44s" transform="skewY(10)"/>
<rect class="bar randomBar" x="497.0" y="339.0" width="18" height="161.0" fill="url(#barGradLow)" style="animation-delay:0.00s" transform="skewY(10)"/>
<rect class="bar randomBar" x="526.0" y="302.0" width="18" height="198.0" fill="url(#barGradLow)" style="animation-delay:-0.09s" transform="skewY(10)"/>
<rect class="bar randomBar" x="555.0" y="425.0" width="18" height="75.0" fill="url(#barGradLow)" style="animation-delay:-0.18s" transform="skewY(10)"/>
<rect class="bar randomBar" x="584.0" y="388.0" width="18" height="112.0" fill="url(#barGradLow)" style="animation-delay:-0.27s" transform="skewY(10)"/>
<rect class="bar randomBar" x="98.0" y="351.0" width="18" height="149.0" fill="url(#barGradLow)" style="animation-delay:-0.36s" transform="skewY(10)"/>
<rect class="bar randomBar" x="127.0" y="314.0" width="18" height="186.0" fill="url(#barGradLow)" style="animation-delay:-0.45s" transform="skewY(10)"/>
<rect class="bar randomBar" x="156.0" y="437.0" width="18" height="63.0" fill="url(#barGradLow)" style="animation-delay:-0.54s" transform="skewY(10)"/>
<rect class="bar randomBar" x="185.0" y="400.0" width="18" height="100.0" fill="url(#barGradLow)" style="animation-delay:-0.63s" transform="skewY(10)"/>
<rect class="bar randomBar" x="214.0" y="363.0" width="18" height="137.0" fill="url(#barGradLow)" style="animation-delay:-0.72s" transform="skewY(10)"/>
<rect class="bar randomBar" x="243.0" y="326.0" width="18" height="174.0" fill="url(#barGradLow)" style="animation-delay:-0.81s" transform="skewY(10)"/>
<rect class="bar randomBar" x="272.0" y="449.0" width="18" height="51.0" fill="url(#barGradLow)" style="animation-delay:-0.90s" transform="skewY(10)"/>
<rect class="bar randomBar" x="301.0" y="412.0" width="18" height="88.0" fill="url(#barGradLow)" style="animation-delay:-0.99s" transform="skewY(10)"/>
<rect class="bar randomBar" x="330.0" y="375.0" width="18" height="125.0" fill="url(#barGradLow)" style="animation-delay:-1.08s" transform="skewY(10)"/>
<rect class="bar randomBar" x="359.0" y="338.0" width="18" height="162.0" fill="url(#barGradLow)" style="animation-delay:-1.17s" transform="skewY(10)"/>
<rect class="bar randomBar" x="388.0" y="301.0" width="18" height="199.0" fill="url(#barGradLow)" style="animation-delay:-1.26s" transform="skewY(10)"/>
<rect class="bar randomBar" x="...